import type { Product } from "../../domain/product/product.types.js";

export const demoProducts: Product[] = [
  {
    id: "prod_001",
    slug: "acolchado-lino-natural",
    name: "Acolchado Lino Natural",
    description: "Acolchado demo de textura suave para dormitorio luminoso.",
    category: "acolchados",
    colors: ["beige", "off-white"],
    measures: ["1 plaza", "2 plazas", "queen"],
    options: ["con relleno"],
    price: 130000,
    transferPrice: 110500,
    installments: 3,
    imageUrl: "/images/products/acolchado-lino-natural.svg",
    isNew: true,
    isFeatured: true,
    isActive: true,
    createdAt: "2026-08-18T00:00:00.000Z"
  },
  {
    id: "prod_002",
    slug: "almohadon-verde-oliva",
    name: "Almohadon Verde Oliva",
    description: "Almohadon demo con acento verde oliva para sumar contraste.",
    category: "almohadones",
    colors: ["verde-oliva"],
    measures: ["50 x 50 cm", "60 x 40 cm"],
    options: ["con relleno", "sin relleno"],
    price: 42000,
    transferPrice: 35700,
    installments: 3,
    imageUrl: "/images/products/almohadon-verde-oliva.svg",
    isNew: true,
    isFeatured: false,
    isActive: true,
    createdAt: "2026-08-17T00:00:00.000Z"
  },
  {
    id: "prod_003",
    slug: "cubre-edredon-gris-perla",
    name: "Cubre Edredon Gris Perla",
    description: "Cubre edredon demo en gris claro para una cama neutra.",
    category: "cubre-edredones",
    colors: ["gris"],
    measures: ["2 plazas", "queen", "king"],
    options: ["funda sola"],
    price: 98000,
    transferPrice: 83300,
    installments: 3,
    imageUrl: "/images/products/cubre-edredon-gris-perla.svg",
    isNew: false,
    isFeatured: true,
    isActive: true,
    createdAt: "2026-08-12T00:00:00.000Z"
  },
  {
    id: "prod_004",
    slug: "respaldo-camel",
    name: "Respaldo Camel",
    description: "Respaldo demo tapizado para completar una habitacion calida.",
    category: "respaldos",
    colors: ["beige", "nuez"],
    measures: ["1.40 m", "1.60 m", "1.80 m"],
    options: ["tapizado"],
    price: 210000,
    transferPrice: 178500,
    installments: 6,
    imageUrl: "/images/products/respaldo-camel.svg",
    isNew: false,
    isFeatured: true,
    isActive: true,
    createdAt: "2026-08-10T00:00:00.000Z"
  },
  {
    id: "prod_005",
    slug: "cubrecama-algodon-stone",
    name: "Cubrecama Algodon Stone",
    description: "Cubrecama demo liviano para uso diario.",
    category: "cubrecamas",
    colors: ["gris", "off-white"],
    measures: ["1 plaza", "2 plazas"],
    options: ["sin relleno"],
    price: 76000,
    transferPrice: 64600,
    installments: 3,
    imageUrl: "/images/products/cubrecama-algodon-stone.svg",
    isNew: false,
    isFeatured: false,
    isActive: true,
    createdAt: "2026-08-06T00:00:00.000Z"
  },
  {
    id: "prod_006",
    slug: "pieza-de-cama-cotton",
    name: "Pieza de Cama Cotton",
    description: "Pieza demo tejida para sumar textura al pie de cama.",
    category: "piezas-de-cama",
    colors: ["beige", "verde-oliva"],
    measures: ["1.20 x 2.70 m", "1.40 x 2.70 m"],
    options: ["tejida"],
    price: 89000,
    transferPrice: 75650,
    installments: 3,
    imageUrl: "/images/products/pieza-de-cama-cotton.svg",
    isNew: true,
    isFeatured: false,
    isActive: true,
    createdAt: "2026-08-15T00:00:00.000Z"
  }
];
